# Comprehensive Dependabot Configuration
# This configuration file automates dependency management across multiple ecosystems
# and implements advanced features for a robust CI/CD pipeline.
# 
# For complete documentation on all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Node.js/npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      include: "scope"
    assignees:
      - "project-maintainer"
    reviewers:
      - "security-team"
    ignore:
      - dependency-name: "express"
        versions: ["4.x.x"]
    versioning-strategy: "auto"
    rebase-strategy: "auto"
    target-branch: "develop"
    
  # Python/pip dependencies
  - package-ecosystem: "pip"
    directory: "/python-services"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"
    allow:
      - dependency-type: "direct"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "mock"
        update-types:
          - "minor"
          - "patch"
          
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      
  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "actions"
      
  # Maven dependencies for Java services
  - package-ecosystem: "maven"
    directory: "/java-services"
    schedule:
      interval: "weekly"
    groups:
      spring-framework:
        patterns:
          - "org.springframework.*"
        exclude-patterns:
          - "org.springframework.security.*"
        
  # Terraform modules and providers
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "terraform"

# Custom vulnerability alerts configuration
vulnerability-alerts:
  enabled: true
